version: 2
builds:
  - binary: php-fpm_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - images:
        - ghcr.io/tonmnn/php-fpm_exporter
    tags:
        - "{{ if not .IsNightly }}latest{{ end }}"
        - "{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
        - "{{ .Major }}.{{ .Minor }}"
        - "{{ .Major }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.description": "A prometheus exporter for PHP-FPM."
      "org.opencontainers.image.url": "https://github.com/tonmnn/php-fpm_exporter"
      "org.opencontainers.image.vendor": "tonmnn"

changelog:
  filters:
    exclude:
      - '^docs:'

archives:
  - id: default
    formats: ['binary']
  - id: targz
    formats: ['tar.gz']
