name: Test Push
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'releases/*'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: 1.23.2
      id: go

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6.1.0
      with:
        version: v1.61

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: 1.23.2
      id: go

    - name: Checkout
      uses: actions/checkout@v4

    - name: Test
      run: go test -coverprofile cover.out ./...

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  image-scan:
    name: Image Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: 1.23.2
      id: go

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Scan image
      uses: anchore/scan-action@v4.1.2
      id: scan
      with:
        image: "ghcr.io/tonmnn/php-fpm_exporter:0.0.0-amd64"
        fail-build: false

    - name: Upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
