name: Test Push
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'releases/*'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5.2.0
      with:
        go-version: 1.23.2
      id: go

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6.1.1
      with:
        version: v1.61

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v5.2.0
      with:
        go-version: 1.23.2
      id: go

    - name: Checkout
      uses: actions/checkout@v4

    - name: Test
      run: go test -coverprofile cover.out ./...

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  image-scan:
    name: Image Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v5.2.0
      with:
        go-version: 1.23.2
      id: go

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      id: build
      with:
        version: v2
        args: release --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract snapshot image name
      id: extract
      run: |
        echo "SNAPSHOT_IMAGE_NAME=$(echo '${{ steps.build.outputs.artifacts }}' \
        | jq '.[] | select(.goos=="linux" and .goarch=="amd64" and .type=="Docker Image") | .name' -r)" \
        >> "$GITHUB_OUTPUT"

    - name: Scan image
      uses: anchore/scan-action@v6.0.0
      id: scan
      with:
        image: ${{ steps.extract.outputs.SNAPSHOT_IMAGE_NAME }}
        fail-build: false

    - name: Upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
